# Site settings
title: Lalit Surampudi blog
email: 
description: "Applied Data Science and Machine Learning."
baseurl: ""
url: "http://datagodzilla.github.io"
linkedin_username: lalitsurampudi
twitter_username: lalitsurampudi
github_username:  lalitsurampudi

comments:
  provider: "disqus"
  disqus:
    shortname: "https-datagodzilla-github-io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: false
  syntax_highlighter: rouge

theme: jekyll-theme-midnight