# Site settings
title: Lalit Surampudi blog
email: lsurampudi@gmail.com
description: "Applied Data Science and Machine Learning"
baseurl: ""
url: "http://datagodzilla.github.io"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: 

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  facebook:
  flickr:
  github: lalitsurampudi
  instagram:
  linkedin: lalitsurampudi
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: lalitsurampudi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
