# Site settings
title: Lalit Surampudi blog
email: lsurampudi@gmail.com
description: "Applied Data Science and Machine Learning"
baseurl: ""
url: "http://datagodzilla.github.io"
linkedin_username: lalitsurampudi
twitter_username: lalitsurampudi
github_username:  lalitsurampudi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
