# Site settings
title: L S blog
email: 
description: "Description goes here.."
baseurl: ""
url: "http://datagodzilla.github.io"
twitter_username: placeholder
github_username:  placeholder

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
